### ISSUE TITLE
**Issue Title:** Compilation Challenges with PyTorch for RTX 5070 Ti (sm_129) on WSL - Seeking Guidance

### ISSUE THREAD

**Issue by kaworukevin** [lllyasviel/FramePack#406]
**Environment:**
- OS: Windows 11 with WSL (Ubuntu 22.04)
- GPU: NVIDIA GeForce RTX 5070 Ti (sm_129)
- CUDA: 12.8
- PyTorch Version: 2.8.0a0+gitc8b4a39 (compiled from source)

**Description:**
Hi FramePack team,

I’m attempting to run FramePack on WSL (Ubuntu 22.04) with an NVIDIA GeForce RTX 5070 Ti (sm_129), but I’ve encountered several challenges while compiling PyTorch from source, which FramePack depends on. Over the past three days, I’ve been troubleshooting with the help of Grok (an AI by xAI) and referencing approaches from an engineer named "woctordho." I’d like to share my process and seek your guidance on whether my approach is correct.

### Steps Taken
1. **Initial Setup and Issues:**
   - Installed PyTorch 2.8.0+cu126 (nightly) with CUDA 12.6, but faced two issues:
     - Dependency conflict: `xformers 0.0.29.post1` required `torch<=2.5.1`, incompatible with my version.
     - PyTorch didn’t support `sm_129`, only supporting `sm_50` to `sm_90`.
   - Attempted to resolve the conflict by reinstalling `xformers`, but the GPU architecture issue persisted (inspired by woctordho’s dependency debugging approach).

2. **Compiling PyTorch from Source:**
   - Cloned PyTorch and set `TORCH_CUDA_ARCH_LIST="12.9"` to support `sm_129`:
     ```
     git clone --recursive https://github.com/pytorch/pytorch.git
     export CUDA_HOME=/usr/local/cuda-12.6
     export PATH=$CUDA_HOME/bin:$PATH
     export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
     export TORCH_CUDA_ARCH_LIST="12.9"
     python setup.py develop
     ```
   - Faced issues like `git` errors (resolved by fixing directories) and `Killed` errors due to memory constraints, mitigated by reducing parallel jobs (`MAX_JOBS=4`), a method suggested by woctordho.

3. **Adjusting GPU Architecture:**
   - NCCL compilation failed with `nvcc fatal: Unsupported gpu architecture 'compute_129'` as CUDA 12.8 doesn’t support `sm_129`.
   - Upgraded to CUDA 12.8 and set `TORCH_CUDA_ARCH_LIST="9.0"` (sm_90, supported by CUDA 12.8), allowing NCCL to compile (following woctordho’s fallback architecture advice).
   - Flash Attention compilation failed with `Killed`. Reduced parallel jobs further and fixed syntax issues with Grok’s help.
   - Currently running: `python setup.py develop > pytorch_compile_log_sm90_j4_corrected.txt 2>&1` with `TORCH_CUDA_ARCH_LIST="9.0"` and `MAX_JOBS=4`.

### Questions
1. Is using `sm_90` instead of `sm_129` reasonable for FramePack? Will this impact performance significantly on my RTX 5070 Ti?
2. Are there specific FramePack dependencies or configurations I should adjust for this setup?
3. Any recommendations to manage memory issues during PyTorch compilation on WSL?

I’ve been saving all outputs to logs for debugging, as suggested by Grok. Any feedback would be greatly appreciated!

Thanks,  
Kevin

**Comment by woct0rdho** [comment]
Why do you need to compile PyTorch from source? It's definitely not needed for most people.

Note that RTX 50xx (also known as Blackwell or sm120) only works with CUDA >= 12.8 .

There is the wheel of torch 2.7.0+cu128 for either Windows or WSL. Do you have issues if you install the wheel?

**Comment by kaworukevin** [comment]
Hi @woct0rdho,

Thank you for your response and suggestions! I appreciate your insights and
would like to clarify our situation and the challenges we're facing.

### Why We Need to Compile PyTorch from Source
We are trying to run FramePack on a system with an NVIDIA GeForce RTX 5070
Ti, which has a compute capability of `sm_129` (Ada Lovelace architecture,
not Blackwell/`sm_120` as mentioned). Initially, we tried using pre-built
PyTorch wheels (version 2.8.0+cu126) in a Windows 11 environment, but we
encountered the following error:

```
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_129 is not compatible
with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70
sm_75 sm_80 sm_86 sm_90.
```

Since the pre-built PyTorch wheels (even the nightly versions we tested) do
not support `sm_129`, we switched to a WSL environment (Ubuntu 22.04) and
attempted to compile PyTorch 2.8.0a0 (nightly) from source with
`TORCH_CUDA_ARCH_LIST="12.9"` to add support for our GPU. We also tried
falling back to `sm_90` (using `TORCH_CUDA_ARCH_LIST="9.0"`) to proceed,
but we are concerned about potential performance impacts.

### Issues with Compiling PyTorch from Source in WSL
While compiling PyTorch from source in WSL, we successfully completed the
build process (using `cmake` and `ninja`), but we consistently encounter
the following error during the `running develop` phase (both with `python
setup.py develop` and `pip install -e .`):

```
running egg_info
error: Cannot update time stamp of directory 'torch_egg-info'
```

We have tried several approaches to resolve this issue, including:
- Ensuring all directories (`framepack/`, `FramePack/`, `pytorch/`, etc.)
have correct permissions (`kaworukevin:kaworukevin`).
- Enabling the `metadata` option in WSL (`/etc/wsl.conf`) to improve
permission mapping.
- Manually creating the `torch_egg-info` directory and updating its
timestamp.
- Using `pip install -e .` instead of `python setup.py develop` to avoid
`easy_install`.

Despite these efforts, the error persists, which we believe is due to WSL's
filesystem limitations (our working directory is on `/mnt/c/`, a Windows
NTFS partition). We are considering moving the directory to a Linux-native
filesystem (e.g., `/home/kaworukevin/`) to see if that resolves the issue,
but we wanted to seek your advice first.

### Questions and Further Guidance
1. **Support for `sm_129` in Pre-built Wheels**: Do you know if any recent
PyTorch nightly wheels support `sm_129` for CUDA 12.8? If so, we would
prefer to use a pre-built version to avoid these compilation issues.
2. **Falling Back to `sm_90`**: Since PyTorch 2.7.0+cu128 supports `sm_90`,
we can compile with `TORCH_CUDA_ARCH_LIST="9.0"` as a fallback. However, we
are concerned about the performance impact on our RTX 5070 Ti. Would this
significantly affect FramePack's performance?
3. **Compiling in WSL**: Do you have any suggestions for resolving the
`Cannot update time stamp of directory 'torch_egg-info'` error in WSL?
Would moving the working directory to a Linux-native filesystem (e.g.,
`/home/kaworukevin/`) likely resolve this issue?

Thank you again for your help! We really appreciate your guidance in
resolving this issue.

Best regards,
Kevin

woctordho ***@***.***> 於 2025年4月29日 週二 下午12:38寫道：

**Comment by woct0rdho** [comment]
It seems you see 'CUDA 12.9' in nvidia-smi. That's the 'CUDA version' (usually there are CUDA 11.8/12.1/12.4/12.6/12.8...), and that's different from the 'compute capability' (also known as 'CUDA arch' or 'sm', usually there are sm75/sm80/sm86/sm89/sm90/sm100/sm120...). There is definitely not sm129, unless you're using some weird modified hardware/driver.

Also, the CUDA version in nvidia-smi is the highest CUDA version that your hardware/driver supports. It can be higher than the actual CUDA version you install.

What you need is torch 2.7.0+cu128.

Also note that the stable version of torch 2.7 is released. Most people don't need the nightly version of torch 2.8 .

**Comment by kaworukevin** [comment]
Thank you again for your guidance! Following your suggestion, I have
successfully installed the pre-built PyTorch 2.7.0+cu128 wheel in my WSL
environment (Ubuntu 22.04), and I no longer need to compile from source
since the RTX 5070 Ti has a compute capability of sm_90, which is supported
by PyTorch 2.7.0.

However, I encountered an unexpected issue during verification. After
installing PyTorch 2.7.0+cu128, I ran the following command to verify the
installation:

python -c "import torch; print(torch.__version__);
print(torch.cuda.is_available());
print(torch.cuda.get_device_capability())"

The output was:

2.7.0+cu128
True
(12, 0)

While torch.cuda.is_available() returns True, indicating that the GPU is
recognized, the reported compute capability is (12, 0) (i.e., sm_120),
which corresponds to the Blackwell architecture. This is inconsistent with
the RTX 5070 Ti, which should have a compute capability of sm_90 (Ada
Lovelace architecture). Since PyTorch 2.7.0 only supports up to sm_90, I am
concerned that this mismatch might cause performance issues or runtime
errors when running FramePack.

To investigate further, I checked the compute capability reported by
nvidia-smi:

nvidia-smi --query-gpu=compute_cap --format=csv

The output was:

compute_cap
12.0

This matches PyTorch's report of (12, 0), but contradicts the expected sm_90
for the RTX 5070 Ti. I also confirmed that nvidia-smi reports the CUDA
version as 12.9, and my installed CUDA toolkit is 12.8, which aligns with
PyTorch 2.7.0+cu128. I suspect this might be an issue with the NVIDIA
driver misreporting the compute capability.
Questions

   1.

   *Compute Capability Mismatch*: Have you encountered cases where
   nvidia-smi and PyTorch misreport the compute capability of the RTX 5070
   Ti as sm_120 instead of sm_90? Could this be a bug in the NVIDIA driver,
   or is it related to my CUDA setup?
   2.

   *Impact on FramePack*: If PyTorch uses sm_120 instead of sm_90, will
   this significantly impact FramePack's performance or stability?
   3.

   *Next Steps*: Should I try updating my NVIDIA driver to see if the
   compute capability is reported correctly, or do you recommend trying a
   different PyTorch version (e.g., a newer nightly build)?

Thank you for your continued support! I really appreciate your help in
resolving this.

Best regards,
Kevin

woctordho ***@***.***> 於 2025年4月29日 週二 下午12:59寫道：

**Comment by kaworukevin** [comment]
Hi @woct0rdho,

Thank you for your response and for pointing out the potential error in my
assumption. I sincerely apologize for the confusion regarding the compute
capability of the RTX 5070 Ti.
Clarification on Compute Capability

I initially assumed that the RTX 5070 Ti has a compute capability of sm_90
based on NVIDIA's official CUDA GPUs list (
https://developer.nvidia.com/cuda-gpus), where the RTX 4000 series (such as
the RTX 4090) is listed with sm_90 (Ada Lovelace architecture). I
mistakenly thought the RTX 5070 Ti, as part of the 50xx series, would also
belong to the same architecture. However, after your comment and further
verification, I realized that the RTX 50xx series, including the RTX 5070
Ti, belongs to the Blackwell architecture with a compute capability of
sm_120.

I confirmed this by checking the compute capability reported by nvidia-smi
and PyTorch in my environment:

woctordho ***@***.***> 於 2025年4月29日 週二 下午8:41寫道：

**Comment by woct0rdho** [comment]
PyTorch 2.7.0 supports sm_120 if it's compiled with CUDA 12.8 . You need CUDA 12.8 to run everything with sm_120.

'command not found' may be because gradio tries to open the browser but you did not install the browser in WSL.

At this point it's actually easier to install it on Windows, because it will take a lot of memory and it's easier to manage the memory on Windows.

If you really want to run it on WSL, then it opens the port 7860, and you can access that port from the browser on Windows, see  https://learn.microsoft.com/en-us/windows/wsl/networking

**Comment by kaworukevin** [comment]
Hello @woct0rdho, could you please help me figure out where the issue might
be? #425 <https://github.com/lllyasviel/FramePack/issues/425> I sincerely
appreciate your assistance.

woctordho ***@***.***> 於 2025年4月30日 週三 上午7:01寫道：
